defmodule Badge.Icons do
  @moduledoc """
  Shape icons as `rgba8888` binaries, expanded from ASCII art by the host
  compiler.

  Art is 16x16; `#` is the accent colour and `.` is the background. Every
  pixel is fully opaque, which keeps AtomGL on its no-blend fast path and
  costs nothing visually because the page background is the same colour.

  Icons draw at 32x32 through a 2x scale, so the stored art is a quarter
  the size of the pixels on the panel.
  """

  alias Badge.Theme

  @size 16
  @scale 2

  @accent Theme.accent()
  @bg Theme.bg()

  @accent_px <<div(@accent, 0x10000), div(rem(@accent, 0x10000), 0x100), rem(@accent, 0x100),
               0xFF>>
  @bg_px <<div(@bg, 0x10000), div(rem(@bg, 0x10000), 0x100), rem(@bg, 0x100), 0xFF>>

  @art %{
    square: """
    ................
    ................
    ..############..
    ..############..
    ..##........##..
    ..##........##..
    ..##........##..
    ..##........##..
    ..##........##..
    ..##........##..
    ..##........##..
    ..############..
    ..############..
    ................
    ................
    ................
    """,
    triangle: """
    ................
    .......##.......
    .......##.......
    ......####......
    ......####......
    .....######.....
    .....######.....
    ....########....
    ....########....
    ...##########...
    ...##########...
    ..############..
    ..############..
    .##############.
    ................
    ................
    """,
    cross: """
    ................
    .##..........##.
    .###........###.
    ..###......###..
    ...###....###...
    ....###..###....
    .....######.....
    ......####......
    ......####......
    .....######.....
    ....###..###....
    ...###....###...
    ..###......###..
    .###........###.
    .##..........##.
    ................
    """,
    circle: """
    ................
    .....######.....
    ...##########...
    ..####....####..
    ..###......###..
    .###........###.
    .##..........##.
    .##..........##.
    .##..........##.
    .##..........##.
    .###........###.
    ..###......###..
    ..####....####..
    ...##########...
    .....######.....
    ................
    """,
    clover: """
    ................
    ....###..###....
    ...##########...
    ...##########...
    ...##########...
    ....###..###....
    ......####......
    .....######.....
    ....########....
    .....######.....
    ......####......
    .......##.......
    ......###.......
    .....####.......
    ................
    ................
    """,
    diamond: """
    ................
    .......##.......
    ......####......
    .....######.....
    ....########....
    ...##########...
    ..############..
    .##############.
    .##############.
    ..############..
    ...##########...
    ....########....
    .....######.....
    ......####......
    .......##.......
    ................
    """,
    dot: """
    ................
    .....######.....
    ...##########...
    ..############..
    ..############..
    .##############.
    .##############.
    .##############.
    .##############.
    .##############.
    .##############.
    ..############..
    ..############..
    ...##########...
    .....######.....
    ................
    """
  }

  # Expanded on the host, where the full standard library is available.
  @icons (for {name, art} <- @art, into: %{} do
            rows = String.split(art, "\n", trim: true)

            length(rows) == @size ||
              raise "icon #{name}: #{length(rows)} rows, expected #{@size}"

            Enum.each(rows, fn row ->
              byte_size(row) == @size ||
                raise "icon #{name}: a row is #{byte_size(row)} wide, expected #{@size}"
            end)

            pixels =
              for row <- rows, into: <<>> do
                for <<char <- row>>, into: <<>> do
                  case char do
                    ?# -> @accent_px
                    ?. -> @bg_px
                  end
                end
              end

            {name, pixels}
          end)

  @names Map.keys(@icons)

  @doc "The raw `rgba8888` binary for one icon, or nil if there is no such icon."
  def binary(name), do: Map.get(@icons, name)

  @doc "Every icon name."
  def names, do: @names

  @doc "Rendered size in pixels, after scaling."
  def size, do: @size * @scale

  @doc "A display item drawing `name` with its top-left corner at `x, y`."
  def item(name, x, y) do
    {:scaled_cropped_image, x, y, @size * @scale, @size * @scale, @bg, 0, 0, @scale, @scale, [],
     {:rgba8888, @size, @size, Map.get(@icons, name)}}
  end
end
